### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by aol-nnov** [WeblateOrg/docker-compose#196]
### Describe the issue

was trying to start `weblate/weblate:edge` and `weblate/weblate:latest` with `docker-compose.yml` from this repo

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

bring up stack with aforementioned compose file

see the [weblate.log](https://github.com/WeblateOrg/docker-compose/files/11517707/weblate.log) attached

### Expected behavior

containers are up and running, service is accessible via web

**Comment by aol-nnov** [comment]
Ahem, actually, I was adopting your compose file for docker with swarm mode.

The vanilla version starts, but my swarm variant fails with logs above. Seems, I'm on my own with it, sigh...

**Comment by nijel** [comment]
The log looks like the container is still starting

**Comment by aol-nnov** [comment]
> The log looks like the container is still starting

@nijel unfortunately, not. I've been tracing the logs with `docker logs -f` and the last line in log file above is actually the last message before container mysterious death.

**Comment by aol-nnov** [comment]
And I thought to myself instantly, it could be something with [healthcheck](https://github.com/WeblateOrg/docker/blob/main/Dockerfile#L19)! May be, container is not ready yet so, health check is failing -> swarm detects unhealty container and kills it. I'll try to fiddle with healthcheck timeouts this weekend!

**Comment by aol-nnov** [comment]
Yay, @nijel! I've managed to get over that mysterious container death by adding the following to the stack definition:

```yml
    healthcheck:
      test: ["curl", "--fail", "http://localhost:8080/healthz/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 3m
```

But now container is stuck in the `starting` state (as seen in the portainer app), so, my ingress controller (traefik) does not get necessary configuration labels from it as it expects `running` / `healthy`container...

Despite that I can `docker exec` into container and successfully curl the healthz endpoint...

**Comment by aol-nnov** [comment]
Weird enough, I'm running gitlab on the same swarm without any issues and healthcheck overrides.

Here is a gitlab's healthcheck: https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/docker/Dockerfile#L58-59

**Comment by aol-nnov** [comment]
Aha! the `CMD` part of heathcheck test was missing in my snippet!!

The correct one is as follows

```yaml
healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/healthz/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 3m
```

So, healthcheck timeouts were the issue.
